### ISSUE TITLE
updated Julia code

### ISSUE THREAD

**Issue by stevengj** [isene/O6#1]
FYI, various alternative Julia implementations can be found [here](https://discourse.julialang.org/t/opportunity-to-write-some-idiomatic-julia-code/39702), including an implementation that is about as compact as your Forth code:
```jl
function O6()
    s, t, crit = rand(1:6), 1, false
    s in (1,6) && while ((t′, t) = (t, rand(1:6)); t < 4)
       s += s ≥ 6 ? 1 : -1
       crit |= 1 == t′ == t
    end
    return s, crit ? (s > 6 ? :critical : :fumble) : nothing
end
```

**Comment by isene** [comment]
Thanks! Neat stuff :-)

**Comment by isene** [comment]
I am looking and looking  there's stuff here I'm not quite getting (like t' and the " crit |= 1 == t′ == t "). Would you mind explaining the code a bit. I'm eager to go deeper into Julia.

**Comment by stevengj** [comment]
`t′` is a [valid variable name in Julia](https://docs.julialang.org/en/v1/manual/variables/#Allowed-Variable-Names-1).   You could rename it to `previous_t` if you want — it's just storing the value of `t` from the previous loop iteration.   Julia has extensive Unicode support and people tend to use it, because both the interactive "REPL" environment and most popular Julia editors make it easy to type Unicode math symbols via [tab completion](https://docs.julialang.org/en/v1/stdlib/REPL/#Tab-completion-1).

`|=` has the same meaning as the corresponding operator in C: `a |= b` is shorthand for `a = a | b`: it takes the bitwise "or" (= logical "or" for boolean values) of `a` and `b` and assigns it to `b`.   So, `crit |= 1 == t′ == t` is setting `crit` to `true` if both the current roll (`t`) and the previous roll (`t′`) are equal to `1`, i.e. whether you rolled two 1's in a row.  (Julia, like Python, supports ["chaining" comparisons](https://docs.julialang.org/en/v1/manual/mathematical-operations/#Chaining-comparisons-1) like `==`.)

Because `&&` is a [short-circuit "and" operator](https://en.wikipedia.org/wiki/Short-circuit_evaluation) in Julia, `s in (1,6) && while (...)` is equivalent to:
```jl
if s in (1,6)
    while (t′, t = (t, rand(1:6)); t < 4)
       s += s ≥ 6 ? 1 : -1
       crit |= 1 == t′ == t
    end
end
```
The construction `(statement1; statement2)` in Julia is just a compound statement that executes `statement1` followed by executing `statement2` and "returns" the value of `statement2`.   So, `(t′, t = (t, rand(1:6)); t < 4)` is a little "cheat" to do 3 things in the `while` condition:

1. Assign `t = rand(1:6)` (roll the die)
2. At the same time, setting `t′` to the *previous* value of `t`.
3. return whether `t < 4` (i.e. whether the "roll" was 1–3).

A little math trick here is that we merge the cases of rolling 6 and 1 on the first roll into a single loop, because checking whether you roll 1–3 with a repeated 1 is equivalent to checking whether you roll 4–6 with a repeated 6.

**Comment by isene** [comment]
Changed the output to print and uploaded your version here as an alternative - being more compact and clever.

**Comment by stevengj** [comment]
Not sure if you want to update your README?

**Comment by isene** [comment]
Readme updated to reflect the Julia progress.
